plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file("local.properties")
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

def MY_SECRET_TOKEN = localProperties.getProperty("MY_SECRET_TOKEN", "")
def BASE_URL = localProperties.getProperty("BASE_URL", "")

android {
    namespace 'app.aicalories.foodscan.photocollage'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "app.aicalories.foodscan.photocollage"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "token", "\"${MY_SECRET_TOKEN}\""
        buildConfigField "String", "BASE_URL", "\"${BASE_URL}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        viewBinding true
        buildConfig = true
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    implementation project(':canvaseditor')
    implementation( libs.lottie)
    implementation libs.coil
    implementation libs.android.gif.drawable
    implementation libs.gson

}